</head>
<body class="<%=strpage%> <%=strPageClassName%>">

<div class="device-xs visible-xs"></div>
<div class="device-sm visible-sm"></div>
<div class="device-md visible-md"></div>
<div class="device-lg visible-lg"></div>
<div class="device-xl visible-xl"></div>

<!--begin Youtube Plugin -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.9/es5-shim.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.3/es6-shim.min.js" type="text/javascript"></script>
<script type="text/javascript" src="js/clamp.min.js"></script> <!-- Overflow Hidden on Video Descriptions wrapper script -->
<!-- end Youtube Plugin -->

<a class="top-skip-link" href="#vcard">Skip to main content</a>
